### ISSUE TITLE
Can you provide the list of Supported XEP

### ISSUE THREAD

**Issue by iAakashTomar** [kdcro101/xmpp-bosh-client#2]
here I needed right now:- 
```
Message Archive Management:- 0313
Last Activity:- 0012
Chat Markers:- 0333
Message Carbons:- 0280
Blocking Command:- 0191
Stream Management:-0198
```

**Comment by kdcro101** [comment]
This module doesn't have any XEP implementation per se (only XEP-0199: XMPP Ping).
It is pure BOSH client, so you can probably implement all of them.

When enabled on server (any XEP) you can construct corresponding XML request using `ltxElement`:

```
 const e = new ltxElement("element",{
    attr1: "some_value",
    attr2: "some_other_value"
}) 
```

send it using `client.send(e)` , wait for response using:

```
 client.on("stanza",(e: XmlElement)=>{
    // do something depending on response
})
```

**Comment by iAakashTomar** [comment]
okay 👍

**Comment by kdcro101** [comment]
@iAakashTomar ,

Please update to 0.3.0.
There are some breaking changes.
For angular app import shoud be:
```
import { BoshClient } from "xmpp-bosh-client/browser"; 
```

when using with Node.js import with:
```
import { BoshClient } from "xmpp-bosh-client/node"; 
```

There is section *Stanza building* of `README.md` to help you generate XML stanzas to send request to your XMPP server.
