### ISSUE TITLE
Bosh Client not connecting

### ISSUE THREAD

**Issue by Sevyls** [kdcro101/xmpp-bosh-client#4]
Hi,

I wrote an Angular 7 service and called my connect() method, like your sample code.

All I see in DevTools are the "starting..." Log entry and OPTIONS Requests to the server.

There is no error in the log, just not working.

Kind regards 
Michael

```

export class FinesseRealTimeService {

  connect() {
    const USERNAME = "Agent001@abc.inc";
    const PASSWORD = "PASSWORD";
    const URL = "https://hq-uccx.abc.inc:7443/http-bind/";

    console.log("starting...");

    const connection = new BoshClient(USERNAME, PASSWORD, URL);
    connection.on("error", (e) => {
      console.log("Error connecting");
      console.log(e);
    });
    connection.on("online", () => {
      console.log("Connected successfully ");
    });
    connection.on("ping", () => {
      console.log(`Ping received at ${new Date()}`);
    });

    connection.on("stanza", (stanza) => {
      console.log(`Stanza received at ${new Date()}`);
      console.log(stanza);
    });


    connection.on("offline", () => {
      console.log("Is OFFLINE");
    });

    connection.connect();
  }
...
```

**Comment by kdcro101** [comment]
@Sevyls ,

Did you import it with:

```
import { BoshClient, $build } from "xmpp-bosh-client/browser";
```

**Comment by Sevyls** [comment]
Hi @kdcro101 
yes, exactly. 
No reaction other than "starting ...", No timeout, no POST request, just the OPTIONS Requests.

**Comment by Sevyls** [comment]
I added the a ``console.log(connection)`` after the connect statement:

````
r {_events: {…}, _eventsCount: 5, _maxListeners: undefined, jid: "Agent001@abc.inc", password: "ciscopsdt", …}
boshUrl: "https://hq-uccx.abc.inc:7443/http-bind/"
chold: 1
hasNextTick: false
jid: "Agent001@abc.inc"
options: {host: "hq-uccx.abc.inc", port: "7443", path: "/http-bind/", method: "POST", agent: false, …}
password: "ciscopsdt"
pending: []
route: undefined
sessionAttributes:
ack: "3218"
authid: "64677176"
hold: "1"
inactivity: "60"
jid: {username: "Agent001", domain: "abc.inc", resource: undefined, toString: ƒ}
maxpause: "300"
password: "ciscopsdt"
polling: "5"
requests: "4"
rid: 3222
secure: "true"
sid: "64677176"
ver: "1.6"
wait: "60"
xmlns: "http://jabber.org/protocol/httpbind"
xmlns:stream: "http://etherx.jabber.org/streams"
__proto__: Object
sessionSupport: false
state: 2
_events: {error: ƒ, online: ƒ, ping: ƒ, stanza: ƒ, offline: ƒ}
_eventsCount: 5
_maxListeners: undefined
__proto__: r
````

**Comment by kdcro101** [comment]
@Sevyls ,

I think it is CORS kicking in because your angular app and XMPP server are not on same domain  hence OPTIONS request. Check your jabberd server configuration.

What jabberd implementation do you use?
Can you test it locally (127.0.0.1) to see if your setup is  ok?

Let me know how it went.

**Comment by kdcro101** [comment]
@Sevyls ,

Closing this issue. If you run into any problems, open issue.

**Comment by Sevyls** [comment]
Hi @kdcro101, 

sorry for the late answer. 

I'm using Cisco UCCX Sandbox & Cisco Finesse 10.6.

It can't be CORS at this stage as it is whitelisted completely by default:
```
Access-Control-Allow-Headers: Overwrite, Destination, Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control
Access-Control-Allow-Methods: PROPFIND, PROPPATCH, COPY, MOVE, DELETE, MKCOL, LOCK, UNLOCK, PUT, GETLIB, VERSION-CONTROL, CHECKIN, CHECKOUT, UNCHECKOUT, REPORT, UPDATE, CANCELUPLOAD, HEAD, OPTIONS, GET, POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
```

I also tried to proxy the requests and had the same results.

I did get a connection but it failed with state  "BOSH AUTHFAIL" and I am stuck from here, as the credentials are the correct ones and I do not understand the problem.

```
<body xmlns='http://jabber.org/protocol/httpbind'>
  <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
    <not-authorized/>
  </failure>
</body>
```

Any ideas how to debug/analyze further?

Kind regards
sevyls

**Comment by kdcro101** [comment]
@Sevyls ,

This module uses [PLAIN SASL](https://tools.ietf.org/html/rfc4616) for authentication.

You should have it enabled on your XMPP server.
Also be sure your credentials are ok.

**Comment by Sevyls** [comment]
When running the following:
```typescript
const USERNAME = "Agent001@abc.inc";
const PASSWORD = "ciscopsdt";
const URL = "https://hq-uccx.abc.inc:7443/http-bind/";

let connection = new BoshClient(USERNAME, PASSWORD, URL);
    
    connection.on("error", (e) => {
      console.log("Error connecting");
      console.log(e);
    });
    connection.on("online", () => {
      console.log("Connected successfully ");
    });
    connection.on("ping", () => {
      console.log(`Ping received at ${new Date()}`);
    });
    connection.on("offline", () => {
      console.log("Is OFFLINE");
    });
    connection.connect();
```
xmpp-bosh-client does POST the following PLAIN SASL Body:

```xml
<body sid="391c1ecf" rid="7722" xmlns="http://jabber.org/protocol/httpbind">
  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">QWdlbnQwMDFAYWJjLmluYwBBZ2VudDAwMQBjaXNjb3BzZHQ=</auth>
</body>
```

The auth string comes down to base64 decoded: ``Agent001@abc.incAgent001ciscopsdt``
I don't understand why it is putting the Username again without domain into the base64 string, but I didn't check the PLAIN SASL specs yet. 

The string exactly represents the default credentials used here for my Cisco Sandbox:

<img width="529" alt="bildschirmfoto 2018-11-20 um 16 03 22" src="https://user-images.githubusercontent.com/547842/48782160-d62cfc00-ecdd-11e8-90e8-4f3a6d61c07a.png">
